(()=>{
 if(document.getElementById('gameNav'))return;
 const css=document.createElement('style');css.textContent=`
 body{padding-bottom:96px}.topbar{padding:12px 16px}.brand span:last-child{font-weight:850}.top-actions .glass-button{display:none}.account-pill{max-width:44px;padding:4px;background:rgba(255,255,255,.06);border-radius:16px}.account-pill #accountName{display:none}.avatar{width:34px;height:34px}
 .hero{grid-template-columns:1fr auto;align-items:center;min-height:190px;padding:24px}.hero-copy{display:none}.hero h1{font-size:34px;max-width:320px}.hero .eyebrow{font-size:9px}.stats-grid{grid-template-columns:repeat(4,1fr);gap:9px}.stat{padding:13px 7px}.stat small{display:none}.stat b{font-size:18px}.stat span{font-size:15px}.section-head{margin-top:26px}.section-head h2{font-size:18px}.game-body p{display:none}.game-card{min-height:0}.game-art{height:150px}.achievements-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.achievements-grid .achievement{padding:12px}.achievements-grid .achievement small{display:none}
 #phase2,#phase3,#gameSocial{display:none}.game-bottom-nav{position:fixed;left:50%;bottom:12px;transform:translateX(-50%);z-index:100;width:min(460px,calc(100vw - 18px));height:68px;padding:7px;border-radius:25px;border:1px solid rgba(255,255,255,.1);background:rgba(14,15,18,.88);backdrop-filter:blur(24px);-webkit-backdrop-filter:blur(24px);box-shadow:0 18px 55px rgba(0,0,0,.45);display:grid;grid-template-columns:repeat(5,1fr);gap:3px}.game-bottom-nav button{border:0;background:transparent;color:#81848d;border-radius:19px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;font:inherit;cursor:pointer}.game-bottom-nav .nav-icon{font-size:20px;line-height:1}.game-bottom-nav .nav-label{font-size:8px;font-weight:850}.game-bottom-nav button.active{color:#fff;background:rgba(255,255,255,.08)}.game-bottom-nav button.play{background:#ff3045;color:#fff;box-shadow:0 7px 25px rgba(255,48,69,.25)}
 .game-sheet{position:fixed;left:50%;bottom:0;transform:translate(-50%,105%);z-index:110;width:min(500px,100vw);padding:18px 18px calc(92px + env(safe-area-inset-bottom));border-radius:28px 28px 0 0;background:rgba(18,19,22,.97);border:1px solid rgba(255,255,255,.1);box-shadow:0 -20px 60px rgba(0,0,0,.5);transition:transform .25s ease}.game-sheet.open{transform:translate(-50%,0)}.game-sheet h3{margin:0 0 14px;font-size:18px}.game-setting{display:flex;align-items:center;gap:12px;padding:13px 0;border-top:1px solid rgba(255,255,255,.07)}.game-setting button{margin-left:auto}.game-setting small{display:block;color:#858891;font-size:10px;margin-top:3px}.game-toggle{width:44px;height:25px;border:0;border-radius:99px;background:#383a40;padding:3px}.game-toggle.on{background:#ff3045}.game-toggle i{display:block;width:19px;height:19px;border-radius:50%;background:#fff;transition:transform .2s}.game-toggle.on i{transform:translateX(19px)}
 body[data-game-view="discover"] #phase3,body[data-game-view="social"] #gameSocial,body[data-game-view="social"] #phase2,body[data-game-view="progress"] #phase2{display:block}body[data-game-view="discover"] .hero,body[data-game-view="discover"] .stats-grid,body[data-game-view="discover"] .section-head,body[data-game-view="discover"] .games-grid,body[data-game-view="discover"] .achievements-grid,body[data-game-view="social"] .hero,body[data-game-view="social"] .stats-grid,body[data-game-view="social"] .games-grid,body[data-game-view="social"] .achievements-grid,body[data-game-view="social"] .leaderboard,body[data-game-view="progress"] .hero,body[data-game-view="progress"] .stats-grid,body[data-game-view="progress"] .games-grid{display:none}body[data-game-view="social"] #phase2{display:none!important}body[data-game-view="social"] .page{padding-top:8px}body[data-game-view="social"] #gameSocial{display:block}body[data-game-view="social"] .game-bottom-nav button[data-view="social"]{color:#fff;background:rgba(255,255,255,.08)}body[data-game-view="progress"] #phase2 .p2-card:nth-child(-n+3),body[data-game-view="progress"] #phase2 .p2-card:nth-child(6){display:none}
 @media(max-width:600px){.hero{grid-template-columns:1fr}.game-art{height:125px}.hero h1{font-size:29px}.p3-head{margin-top:20px}.p3-head h2{font-size:20px}}
 `;document.head.appendChild(css);
 const nav=document.createElement('nav');nav.id='gameNav';nav.className='game-bottom-nav';nav.setAttribute('aria-label','Game navigation');nav.innerHTML=`<button data-view="home" class="active"><span class="nav-icon">⌂</span><span class="nav-label">Home</span></button><button data-view="discover"><span class="nav-icon">◌</span><span class="nav-label">Discover</span></button><button class="play" data-play="redrush"><span class="nav-icon">▶</span><span class="nav-label">Play</span></button><button data-view="social"><span class="nav-icon">♧</span><span class="nav-label">Social</span></button><button data-more><span class="nav-icon">•••</span><span class="nav-label">More</span></button>`;document.body.appendChild(nav);
 const sheet=document.createElement('section');sheet.className='game-sheet';sheet.id='gameSheet';sheet.innerHTML=`<h3>Game</h3><div class="game-setting"><div>🔊 Sound<small>On by default. No sound setting is saved on the device.</small></div><button class="game-toggle on" id="gameSoundToggle" aria-label="Toggle sound"><i></i></button></div><div class="game-setting"><div>👤 Redlighte Account<small>Use your connected account.</small></div><button class="tiny" id="gameAccount">Open</button></div><div class="game-setting"><div>⛶ Fullscreen<small>App-like view.</small></div><button class="tiny" id="gameFullscreen">Enter</button></div><div class="game-setting"><div>↩ Exit Game<small>Back to Redlighte.</small></div><button class="tiny" id="gameExit">Exit</button></div>`;document.body.appendChild(sheet);
 function setView(v){document.body.dataset.gameView=v;nav.querySelectorAll('button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));sheet.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
 nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)setView(b.dataset.view);if(b.dataset.play)window.RedlighteGame?.play(b.dataset.play);if(b.hasAttribute('data-more'))sheet.classList.toggle('open')});
 document.getElementById('gameSoundToggle').onclick=()=>{const b=document.getElementById('gameSoundToggle');b.classList.toggle('on');window.dispatchEvent(new CustomEvent('redlighte-game-sound',{detail:{enabled:b.classList.contains('on')}}));if(b.classList.contains('on'))window.dispatchEvent(new Event('redlighte-game-sound-ping'))};
 document.getElementById('gameAccount').onclick=()=>location.href='/?account=login';
 document.getElementById('gameFullscreen').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch{}};
 document.getElementById('gameExit').onclick=()=>location.href='/';
 document.addEventListener('click',e=>{if(!e.target.closest('#gameSheet')&&!e.target.closest('[data-more]'))sheet.classList.remove('open')});
 window.addEventListener('redlighte-game-sound-ping',()=>{try{const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=640;g.gain.value=.025;o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+.06)}catch{}});
 const forceSound=()=>{const s=document.getElementById('p3Sound');if(s&&!s.classList.contains('on'))s.click()};setTimeout(forceSound,900);setTimeout(forceSound,2200);
})();