(()=>{
const mount=()=>document.querySelector('#gameMount'),modal=()=>document.querySelector('#gameModal'),toast=()=>document.querySelector('#toast');
const say=t=>{const x=toast();if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
let raf=0,timer=0,score=0,combo=0,best=0,started=false,ended=false,target=null,arena=null;
const finish=win=>{if(ended)return;ended=true;cancelAnimationFrame(raf);clearInterval(timer);const s=Math.max(0,Math.round(score));window.RedlighteGame?.finish?.('red-dash',s,!!win);setTimeout(()=>{const b=document.querySelector('#rdBest');if(b)b.textContent=Math.max(best,s)},50)};
function moveTarget(){if(!target||!arena)return;const r=arena.getBoundingClientRect(),size=target.offsetWidth,pad=8;target.style.left=(pad+Math.random()*Math.max(1,r.width-size-pad*2))+'px';target.style.top=(pad+Math.random()*Math.max(1,r.height-size-pad*2))+'px'}
function spawn(){if(ended)return;moveTarget();const speed=Math.max(420,900-score*4-combo*18);clearTimeout(spawn.t);spawn.t=setTimeout(spawn,speed)}
function hit(){if(ended)return;combo++;score+=10+Math.min(40,combo*2);const s=document.querySelector('#rdScore'),c=document.querySelector('#rdCombo');if(s)s.textContent=score;if(c)c.textContent='x'+combo;target.classList.remove('rd-hit');void target.offsetWidth;target.classList.add('rd-hit');moveTarget();spawn()}
function miss(){if(ended)return;combo=0;const c=document.querySelector('#rdCombo');if(c)c.textContent='x0';score=Math.max(0,score-5);const s=document.querySelector('#rdScore');if(s)s.textContent=score}
function start(){if(started)return;started=true;ended=false;score=0;combo=0;let left=30;const t=document.querySelector('#rdTime');t.textContent=left;moveTarget();spawn();timer=setInterval(()=>{left--;t.textContent=left;if(left<=0)finish(score>=250)},1000)}
function render(){const m=mount(),mo=modal();if(!m||!mo)return;m.innerHTML=`<div class="red-dash"><div class="rd-head"><div><span class="rd-kicker">REDLIGHTE ORIGINAL</span><h2>Red Dash</h2><p>Catch the red pulse before it moves. Build combos. Chase your best.</p></div><div class="rd-stats"><b id="rdScore">0</b><small>SCORE</small><b id="rdTime">30</b><small>SEC</small></div></div><div class="rd-arena" id="rdArena"><div class="rd-grid"></div><button class="rd-target" id="rdTarget" aria-label="Catch target"></button><div class="rd-combo" id="rdCombo">x0</div></div><div class="rd-bottom"><span>🎯 <b>+10</b> base · combo bonus grows</span><button class="rd-start" id="rdStart">START RUN</button></div><div class="rd-tip">Tap the pulse. Missing costs 5 points. Reach <b>250</b> to win. 🏆</div></div>`;arena=document.querySelector('#rdArena');target=document.querySelector('#rdTarget');target.addEventListener('click',e=>{e.stopPropagation();hit()});arena.addEventListener('click',e=>{if(e.target===arena)miss()});document.querySelector('#rdStart').addEventListener('click',start);mo.hidden=false;}
window.RedlighteRedDash={start:render};
})();