const $=s=>document.querySelector(s);const home=$('#home'),roomView=$('#room'),toast=$('#toast');let me=null,roomId=null,ws=null,presence=null,currentRoom=null,pendingInvite=null;
const api=async(path,opt={})=>{const r=await fetch(path,{credentials:'include',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let b=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.error||`Request failed (${r.status})`);return b};
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setRoom(id){history.pushState({},'',`/room/${id}`);roomId=id;home.classList.add('hidden');roomView.classList.remove('hidden');$('#roomCodeLabel').textContent=`ROOM ${id}`;connectRoom();connectPresence();}
async function boot(){try{const x=await api('/api/room/me');me=x.user;$('#identity').textContent=`${me.name} · @${me.username}`;loadInvitations();const match=location.pathname.match(/^\/room\/([A-Za-z0-9_-]+)$/);if(match){roomId=match[1];home.classList.add('hidden');roomView.classList.remove('hidden');$('#roomCodeLabel').textContent=`ROOM ${roomId}`;connectRoom();connectPresence();}}catch{location.href='/login?redirect=/room'}}
async function create(){try{const x=await api('/api/room/create',{method:'POST'});setRoom(x.room.id);showToast('Room created 🔴')}catch(e){showToast(e.message)}}
async function joinCode(){let id=$('#joinCode').value.trim().toUpperCase();if(!id)return;try{await api(`/api/room/${encodeURIComponent(id)}/join`,{method:'POST',body:'{}'});setRoom(id);showToast('Joined room')}catch(e){showToast(e.message)}}
function connectRoom(){if(ws)ws.close();const proto=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${proto}://${location.host}/api/room/${roomId}/ws`);ws.onopen=()=>ws.send(JSON.stringify({type:'SYNC_REQUEST'}));ws.onmessage=e=>handleRoom(JSON.parse(e.data));ws.onclose=()=>{if(roomView.classList.contains('hidden'))return;setTimeout(()=>roomId&&connectRoom(),1800)};ws.onerror=()=>showToast('Room connection interrupted')}
function connectPresence(){if(presence)presence.close();const proto=location.protocol==='https:'?'wss':'ws';presence=new WebSocket(`${proto}://${location.host}/api/room/presence/ws`);presence.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='INVITATION'){showInvitation(m.invitation);loadInvitations()}}}
function handleRoom(m){if(m.type==='ROOM_STATE'){currentRoom=m.room;renderRoom();applyContent(m.room.content);syncPlayback(m.room.playback||{});applyFullscreen(m.room.fullscreen);return}if(m.type==='CONTENT_CHANGE'){if(currentRoom){currentRoom.content=m.content;currentRoom.playback={playing:false,position:0,updatedAt:Date.now()}}applyContent(m.content);updateSeek(0);return}if(m.type==='MEMBER_JOINED'){if(currentRoom)currentRoom.members=m.members;renderMembers();showToast(`${m.user.name} joined`);return}if(m.type==='PRESENCE'){if(currentRoom){currentRoom.members=currentRoom.members.map(x=>x.username===m.username?{...x,online:m.online}:x);renderMembers()};return}if(m.type==='PLAY'||m.type==='PAUSE'||m.type==='SEEK'){syncPlayback(m);return}if(m.type==='FULLSCREEN'){if(currentRoom)currentRoom.fullscreen=m.enabled;applyFullscreen(m.enabled);return}if(m.type==='CHAT'){appendMessage(m.message);return}if(m.type==='REACTION'){floatReaction(m.emoji);return}if(m.type==='ROOM_CLOSED'){showToast('Room closed by host');setTimeout(()=>location.href='/room',900)}}
function renderRoom(){if(!currentRoom)return;$('#count').textContent=currentRoom.members.length;renderMembers();$('#messages').innerHTML='';(currentRoom.chat||[]).forEach(appendMessage);updateSeek(currentRoom.playback?.position||0)}
function renderMembers(){const box=$('#members');box.innerHTML=(currentRoom?.members||[]).map(u=>`<div class="member"><div class="member-info"><span class="avatar">${escapeHtml((u.name||u.username)[0]?.toUpperCase())}</span><div>${escapeHtml(u.name||u.username)}<small>@${escapeHtml(u.username)} · ${u.username===currentRoom?.owner?.username?'Host':(u.online?'Online':'Member')}</small></div></div></div>`).join('')}
function applyContent(content){const frame=$('#webFrame'),vid=$('#video'),empty=$('#emptyViewer');if(!content){empty.classList.remove('hidden');frame.classList.add('hidden');vid.classList.add('hidden');return}empty.classList.add('hidden');$('#url').value=content.url;const u=content.url;const yt=u.match(/(?:youtube\.com\/(?:watch\?v=|embed\/)|youtu\.be\/)([A-Za-z0-9_-]{6,})/i);if(yt){frame.src=`https://www.youtube.com/embed/${yt[1]}?enablejsapi=1&origin=${encodeURIComponent(location.origin)}&autoplay=0`;frame.classList.remove('hidden');vid.classList.add('hidden');return}if(/\.(mp4|webm|ogg)(?:$|\?)/i.test(u)||/^https?:\/\/.*\.(m3u8)(?:$|\?)/i.test(u)){vid.src=u;vid.classList.remove('hidden');frame.classList.add('hidden');return}frame.src=u;frame.classList.remove('hidden');vid.classList.add('hidden')}
function send(m){if(ws?.readyState===1)ws.send(JSON.stringify(m))}
function loadContent(){const u=$('#url').value.trim();if(!u)return;let provider='website';if(/youtube\.com|youtu\.be/i.test(u))provider='youtube';else if(/\.(mp4|webm|ogg|m3u8)(?:$|\?)/i.test(u))provider='media';send({type:'CONTENT_CHANGE',url:u,provider,title:u})}
function syncPlayback(m){const vid=$('#video');if(vid.classList.contains('hidden'))return;let target=Number(m.position||0);if(m.playing&&m.updatedAt)target+=Math.max(0,(Date.now()-Number(m.updatedAt))/1000);if(m.serverTime&&m.type&&m.type!=='SEEK'&&m.type!=='ROOM_STATE'&&m.type!=='PAUSE')target+=Math.max(0,(Date.now()-Number(m.serverTime))/1000);if(Math.abs(vid.currentTime-target)>0.35)vid.currentTime=target;if(m.type==='PLAY'||(m.playing&&m.type==='ROOM_STATE'))vid.play().catch(()=>{});if(m.type==='PAUSE'||(m.playing===false&&m.type==='ROOM_STATE'))vid.pause();updateSeek(target)}
function updateSeek(s){$('#seek').value=Math.min(100,Math.max(0,Number(s)||0));$('#time').textContent=formatTime(Number(s)||0)}
function formatTime(s){s=Math.max(0,Math.floor(s));return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function appendMessage(m){const box=$('#messages');box.insertAdjacentHTML('beforeend',`<div class="msg"><b>${escapeHtml(m.user?.name||m.user?.username)}</b><p>${escapeHtml(m.text)}</p></div>`);box.scrollTop=box.scrollHeight}
function floatReaction(e){const n=document.createElement('div');n.textContent=e;n.style.cssText='position:fixed;right:26%;bottom:20%;font-size:42px;z-index:60;animation:float 1.4s ease forwards';document.body.appendChild(n);setTimeout(()=>n.remove(),1400)}
function showInvitation(inv){pendingInvite=inv;$('#inviteTitle').textContent=`${inv.from.name} invited you`;$('#inviteText').textContent=`Join room ${inv.roomId} and watch together.`;$('#incoming').classList.remove('hidden')}
async function loadInvitations(){try{const x=await api('/api/room/invitations');renderInvitations(x.invitations||[])}catch(e){showToast(e.message)}}
function renderInvitations(list){const box=$('#invitations');if(!list.length){box.innerHTML='<div class="empty-invites">No pending invitations.</div>';return}box.innerHTML=list.map(i=>`<div class="invite-card"><div><b>${escapeHtml(i.from.name||i.from.username)}</b><span>@${escapeHtml(i.from.username)} invited you to <strong>ROOM ${escapeHtml(i.roomId)}</strong></span></div><div class="invite-actions"><button class="secondary invite-decline" data-id="${escapeHtml(i.id)}">Decline</button><button class="primary invite-accept" data-id="${escapeHtml(i.id)}">Join room</button></div></div>`).join('')}
async function handleStoredInvite(id,decision){try{const x=await api(`/api/room/invitations/${encodeURIComponent(id)}`,{method:'POST',body:JSON.stringify({decision})});if(decision==='accept'){await api(`/api/room/${x.invitation.roomId}/join`,{method:'POST',body:'{}'});setRoom(x.invitation.roomId);showToast('Joined room 🔴')}else showToast('Invitation declined');loadInvitations()}catch(e){showToast(e.message);loadInvitations()}}
async function acceptInvite(){if(!pendingInvite)return;try{await api(`/api/room/invitations/${encodeURIComponent(pendingInvite.id)}`,{method:'POST',body:JSON.stringify({decision:'accept'})});await api(`/api/room/${pendingInvite.roomId}/join`,{method:'POST',body:'{}'});$('#incoming').classList.add('hidden');setRoom(pendingInvite.roomId);pendingInvite=null}catch(e){showToast(e.message)}}
async function searchUsers(){const q=$('#userSearch').value.trim();try{const x=await api(`/api/room/users?q=${encodeURIComponent(q)}`);$('#userResults').innerHTML=x.users.map(u=>`<div class="user-row"><div class="member-info"><span class="avatar">${escapeHtml(u.username[0].toUpperCase())}</span><span>@${escapeHtml(u.username)}</span></div><button data-user="${escapeHtml(u.username)}">Invite</button></div>`).join('')||'<div class="identity">No users found.</div>'}catch(e){showToast(e.message)}}
async function inviteUser(username){try{await api(`/api/room/${roomId}/invite`,{method:'POST',body:JSON.stringify({username})});showToast('Invitation sent 🔴')}catch(e){showToast(e.message)}}
async function toggleFullscreen(){const enabled=!document.body.classList.contains('room-immersive');send({type:'FULLSCREEN',enabled});if(enabled)await enterFullscreen();else await exitFullscreen()}
async function enterFullscreen(){document.body.classList.add('room-immersive');try{if(!document.fullscreenElement)await $('#playerShell').requestFullscreen();}catch{}try{if(screen.orientation?.lock)await screen.orientation.lock('landscape');}catch{}}
async function exitFullscreen(){document.body.classList.remove('room-immersive');try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}try{if(screen.orientation?.unlock)screen.orientation.unlock()}catch{}}
function applyFullscreen(enabled){if(enabled){document.body.classList.add('room-immersive');enterFullscreen()}else exitFullscreen()}
$('#create').onclick=create;$('#newRoom').onclick=create;$('#joinPrompt').onclick=()=>$('#joinBox').classList.toggle('hidden');$('#join').onclick=joinCode;$('#joinCode').onkeydown=e=>{if(e.key==='Enter')joinCode()};$('#load').onclick=loadContent;$('#url').onkeydown=e=>{if(e.key==='Enter')loadContent()};$('#playPause').onclick=()=>{const v=$('#video');const pos=v.classList.contains('hidden')?Number($('#seek').value):v.currentTime;send({type:v.paused?'PLAY':'PAUSE',position:pos})};$('#seek').onchange=()=>send({type:'SEEK',position:Number($('#seek').value)});$('#chatForm').onsubmit=e=>{e.preventDefault();const input=$('#chatInput');if(input.value.trim())send({type:'CHAT',text:input.value.trim()});input.value=''};$('#invite').onclick=$('#invite2').onclick=()=>{$('#inviteModal').classList.remove('hidden');searchUsers()};$('#userSearch').oninput=searchUsers;$('#userResults').onclick=e=>{const b=e.target.closest('[data-user]');if(b)inviteUser(b.dataset.user)};$('#invitations').onclick=e=>{const a=e.target.closest('[data-id]');if(a)handleStoredInvite(a.dataset.id,a.classList.contains('invite-accept')?'accept':'decline')};$('#refreshInvites').onclick=loadInvitations;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.modal').classList.add('hidden'));$('#accept').onclick=acceptInvite;$('#decline').onclick=async()=>{if(!pendingInvite)return;try{await api(`/api/room/invitations/${encodeURIComponent(pendingInvite.id)}`,{method:'POST',body:JSON.stringify({decision:'decline'})})}catch{}$('#incoming').classList.add('hidden');pendingInvite=null;loadInvitations()};$('#closeRoom').onclick=async()=>{if(confirm('Close this one-time room for everyone?'))try{await api(`/api/room/${roomId}/close`,{method:'POST',body:'{}'})}catch(e){showToast(e.message)}};$('#fullscreen').onclick=toggleFullscreen;document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&!currentRoom?.fullscreen)document.body.classList.remove('room-immersive')});window.onpopstate=()=>location.reload();boot();