(()=>{
const $=s=>document.querySelector(s),json=async(path,opt={})=>{const r=await fetch(path,{credentials:'include',cache:'no-store',...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw Error(b.error||`HTTP ${r.status}`);return b},esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let roomId=null,me=null,room=null,rws=null,lws=null,stream=null,peers=new Map(),ice=new Map(),closing=false,started=false;
const pathRoom=()=>{const m=location.pathname.match(/^\/room\/(.+)$/);if(!m)return null;try{return decodeURIComponent(m[1])}catch{return m[1]}};
const urlWs=p=>`${location.protocol==='https:'?'wss':'ws'}://${location.host}${p}`;
const host=()=>room?.owner?.username===me?.username;
const toast=t=>{const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),1800)};
function render(){if(!room)return;const c=$('#count'),m=$('#members'),box=$('#messages');if(c)c.textContent=(room.members||[]).length;if(m)m.innerHTML=(room.members||[]).map(u=>`<div class="member"><div class="member-info"><span class="avatar">${esc((u.name||u.username)[0]?.toUpperCase())}</span><div>${esc(u.name||u.username)}<small>@${esc(u.username)} · ${u.username===room.owner.username?'Host':'Online'}</small></div></div></div>`).join('');if(box){box.innerHTML='';(room.chat||[]).forEach(addMsg)}}
function addMsg(m){const b=$('#messages');if(!b||!m)return;b.insertAdjacentHTML('beforeend',`<div class="msg"><b>${esc(m.user?.name||m.user?.username)}</b><p>${esc(m.text)}</p></div>`);b.scrollTop=b.scrollHeight}
async function startRoom(id){if(started&&roomId===id)return;started=true;roomId=id;closing=false;try{const a=await json('/api/room/me');me=a.user;await json(`/api/room/${encodeURIComponent(roomId)}/join`,{method:'POST',body:'{}'})}catch{started=false;return}connectRoom();connectLive()}
function stopRoom(){closing=true;try{rws?.close(1000,'navigation');lws?.close(1000,'navigation')}catch{}peers.forEach(p=>p.close());peers.clear();ice.clear();rws=null;lws=null;room=null;roomId=null;started=false;stream?.getTracks().forEach(t=>t.stop());stream=null}
function connectRoom(){if(!roomId)return;try{rws?.close(1000,'replace')}catch{}const s=new WebSocket(urlWs(`/api/room/${encodeURIComponent(roomId)}/ws`));rws=s;s.onopen=()=>s.send(JSON.stringify({type:'SYNC_REQUEST'}));s.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='ROOM_STATE'){room=m.room;render();connectLive();}else if(m.type==='MEMBER_JOINED'||m.type==='MEMBER_LEFT'){if(room)room.members=m.members||[];render();if(host()&&stream&&m.type==='MEMBER_JOINED')offer(m.user?.username)}else if(m.type==='CHAT'){if(room)room.chat=[...(room.chat||[]),m.message].slice(-50);addMsg(m.message)}else if(m.type==='ROOM_CLOSED'){stopShare();location.href='/room'}}catch{}};s.onclose=()=>{if(!closing&&roomId===pathRoom())setTimeout(()=>{if(rws===s)connectRoom()},1500)};s.onerror=()=>{}};
function send(m){if(rws?.readyState===WebSocket.OPEN)try{rws.send(JSON.stringify(m))}catch{}}
function connectLive(){if(!roomId)return;if(lws){try{lws.close(1000,'replace')}catch{}}const s=new WebSocket(urlWs(`/api/room-live/${encodeURIComponent(roomId)}/ws`));lws=s;s.onopen=()=>{if(!host()&&room?.owner?.username)s.send(JSON.stringify({type:'READY',host:room.owner.username}))};s.onmessage=e=>{try{liveMessage(JSON.parse(e.data))}catch{}};s.onclose=()=>{if(!closing&&roomId===pathRoom())setTimeout(()=>{if(lws===s)connectLive()},2500)};s.onerror=()=>{}}
function lsend(m){if(lws?.readyState===WebSocket.OPEN)try{lws.send(JSON.stringify(m))}catch{}}
function peer(name,offerer){if(!name||name===me.username)return null;if(peers.has(name)){try{peers.get(name).close()}catch{}peers.delete(name)}const p=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}]});peers.set(name,p);ice.set(name,[]);p.onicecandidate=e=>e.candidate&&lsend({type:'ICE',to:name,candidate:e.candidate});p.ontrack=e=>{if(host())return;const v=$('#liveVideo');v.srcObject=e.streams[0]||new MediaStream([e.track]);v.classList.remove('hidden');$('#emptyViewer').classList.add('hidden');v.play().catch(()=>{})};p.onconnectionstatechange=()=>{if(['failed','closed'].includes(p.connectionState)&&peers.get(name)===p){peers.delete(name);ice.delete(name)}};if(host()&&stream)stream.getTracks().forEach(t=>p.addTrack(t,stream));if(offerer&&host())p.createOffer().then(o=>p.setLocalDescription(o)).then(()=>lsend({type:'OFFER',to:name,description:p.localDescription})).catch(()=>{});return p}
async function remoteIce(name,c){const p=peers.get(name);if(!p)return;if(p.remoteDescription)try{await p.addIceCandidate(c)}catch{}else ice.get(name)?.push(c)}
async function flush(name){const p=peers.get(name),q=ice.get(name)||[];if(!p)return;for(const c of q)try{await p.addIceCandidate(c)}catch{}q.length=0}
async function liveMessage(m){if(m.type==='LIVE_SIGNAL_READY'&&!host()&&room?.owner?.username)return lsend({type:'READY',host:room.owner.username});if(m.type==='VIEWER_READY'&&host()&&stream)return offer(m.from);if(m.type==='OFFER'&&!host()){const p=peer(m.from,false);if(!p)return;try{await p.setRemoteDescription(m.description);await flush(m.from);const a=await p.createAnswer();await p.setLocalDescription(a);lsend({type:'ANSWER',to:m.from,description:p.localDescription})}catch{}}else if(m.type==='ANSWER'&&host()){const p=peers.get(m.from);if(p)try{await p.setRemoteDescription(m.description);await flush(m.from)}catch{}}else if(m.type==='ICE')await remoteIce(m.from,m.candidate);else if(m.type==='SHARE_STOP'&&!host()){peers.forEach(p=>p.close());peers.clear();ice.clear();const v=$('#liveVideo');v.srcObject=null;v.classList.add('hidden');$('#emptyViewer').classList.remove('hidden')}}
function offer(name){if(name)peer(name,true)}
async function startShare(){if(!host())return;try{stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:30,max:60}},audio:true});const v=$('#liveVideo');v.srcObject=stream;v.classList.remove('hidden');$('#emptyViewer').classList.add('hidden');$('#startShare').classList.add('hidden');$('#startShareEmpty').classList.add('hidden');$('#stopShare').classList.remove('hidden');lsend({type:'SHARE_START'});(room.members||[]).filter(x=>x.username!==me.username).forEach(x=>offer(x.username));stream.getVideoTracks()[0]?.addEventListener('ended',stopShare,{once:true});toast('Live Share is on 🔴')}catch(e){if(e.name!=='NotAllowedError')toast('Could not start Live Share')}}
function stopShare(){if(!stream)return;lsend({type:'SHARE_STOP'});stream.getTracks().forEach(t=>t.stop());stream=null;peers.forEach(p=>p.close());peers.clear();ice.clear();const v=$('#liveVideo');if(v){v.srcObject=null;v.classList.add('hidden')}$('#emptyViewer')?.classList.remove('hidden');$('#startShare')?.classList.remove('hidden');$('#startShareEmpty')?.classList.remove('hidden');$('#stopShare')?.classList.add('hidden')}
function capture(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='startShare'||b.id==='startShareEmpty'){e.preventDefault();e.stopImmediatePropagation();startShare()}else if(b.id==='stopShare'){e.preventDefault();e.stopImmediatePropagation();stopShare()}},true);document.addEventListener('submit',e=>{if(e.target?.id!=='chatForm')return;e.preventDefault();e.stopImmediatePropagation();const i=$('#chatInput'),t=i.value.trim();if(t){send({type:'CHAT',text:t});i.value=''}},true)}
function watchRoute(){const id=pathRoom();if(id&&!started)startRoom(id);else if(!id&&started)stopRoom();else if(id&&started&&id!==roomId){stopRoom();startRoom(id)}}
capture();watchRoute();setInterval(watchRoute,500);
})();