const DATA_REPO='amirsepehr2020/redlighte-data';
export async function handleGameApi(request,env,url){const cors=corsHeaders(request);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const me=await readSession(request,env);if(!me)return json({error:'Unauthorized.'},401,cors);try{if(url.pathname==='/api/game/social'&&request.method==='GET')return social(env,me,cors);if(url.pathname==='/api/game/friends'&&request.method==='POST')return addFriend(request,env,me,cors);if(url.pathname==='/api/game/friends/accept'&&request.method==='POST')return acceptFriend(request,env,me,cors);if(url.pathname==='/api/game/friends/remove'&&request.method==='POST')return removeFriend(request,env,me,cors);if(url.pathname==='/api/game/challenges'&&request.method==='POST')return challenge(request,env,me,cors);if(url.pathname==='/api/game/challenges/respond'&&request.method==='POST')return respond(request,env,me,cors);return json({error:'Not found.'},404,cors)}catch(e){console.error('GAME_API_ERROR',e);return json({error:'Game social service error.'},500,cors)}}
async function social(env,me,cors){const f=await account(env,me.username),s=ensure(f.data);const day=new Date().toISOString().slice(0,10),games=[{id:'redrush',name:'Red Rush',tag:'ARCADE',text:'15 seconds. Beat your record.'},{id:'redlight',name:'Redlight',tag:'REACTION',text:'React only on red.'},{id:'grid',name:'Grid',tag:'PUZZLE',text:'Find the glowing tile.'}];return json({user:me,friends:s.friends,incomingRequests:s.incomingRequests,outgoingRequests:s.outgoingRequests,challenges:s.challenges,events:[{id:'red-week',title:'Red Week',description:'Play Originals and earn bonus XP.',active:true},{id:'rush-hour',title:'Rush Hour',description:'Beat 20 in Red Rush.',active:true}],quests:[{id:'play3',title:'Play 3 Games',target:3,reward:30},{id:'win1',title:'Claim a Win',target:1,reward:50},{id:'score20',title:'Beat 20',target:20,reward:40}],gameOfDay:games[Math.floor(Date.now()/86400000)%games.length],day},200,cors)}
async function addFriend(request,env,me,cors){const b=await request.json(),u=clean(b.username,32).toLowerCase();if(!valid(u)||u===me.username)return json({error:'Invalid username.'},400,cors);const t=await account(env,u);if(!t)return json({error:'Account not found.'},404,cors);const o=await account(env,me.username),s=ensure(o.data),ts=ensure(t.data);if(s.friends.some(x=>x.username===u))return json({error:'Already friends.'},409,cors);if(!s.outgoingRequests.some(x=>x.username===u)){s.outgoingRequests.push({username:u,name:t.data.user.name});ts.incomingRequests.push({username:me.username,name:me.name});await write(env,o,t,'Send friend request');await write(env,t,ts,'Receive friend request')}return json({ok:true},200,cors)}
async function acceptFriend(request,env,me,cors){const b=await request.json(),u=clean(b.username,32).toLowerCase(),o=await account(env,me.username),s=ensure(o.data),t=await account(env,u);if(!t)return json({error:'Account not found.'},404,cors);const ts=ensure(t.data);if(!s.incomingRequests.some(x=>x.username===u))return json({error:'Request not found.'},404,cors);s.incomingRequests=s.incomingRequests.filter(x=>x.username!==u);s.friends.push({username:u,name:t.data.user.name});ts.outgoingRequests=ts.outgoingRequests.filter(x=>x.username!==me.username);ts.friends.push({username:me.username,name:me.name});await write(env,o,'Accept friend');await write(env,t,'Friend accepted');return json({ok:true},200,cors)}
async function removeFriend(request,env,me,cors){const b=await request.json(),u=clean(b.username,32).toLowerCase(),o=await account(env,me.username),s=ensure(o.data);s.friends=s.friends.filter(x=>x.username!==u);await write(env,o,'Remove friend');const t=await account(env,u);if(t){const ts=ensure(t.data);ts.friends=ts.friends.filter(x=>x.username!==me.username);await write(env,t,'Friend removed')}return json({ok:true},200,cors)}
async function challenge(request,env,me,cors){const b=await request.json(),u=clean(b.username,32).toLowerCase(),game=clean(b.game,20);const o=await account(env,me.username),s=ensure(o.data),t=await account(env,u);if(!t||!s.friends.some(x=>x.username===u))return json({error:'You can only challenge a friend.'},403,cors);if(!['redrush','redlight','grid'].includes(game))return json({error:'Invalid game.'},400,cors);const c={id:crypto.randomUUID(),game,from:me.username,fromName:me.name,to:u,status:'pending',createdAt:new Date().toISOString(),scores:{}};s.challenges.push(c);const ts=ensure(t.data);ts.challenges.push({...c});await write(env,o,'Create challenge');await write(env,t,'Receive challenge');return json({challenge:c},201,cors)}
async function respond(request,env,me,cors){const b=await request.json(),o=await account(env,me.username),s=ensure(o.data),c=s.challenges.find(x=>x.id===clean(b.id,80));if(!c||c.to!==me.username)return json({error:'Challenge not found.'},404,cors);c.status=b.accept===true?'accepted':'declined';await write(env,o,'Respond challenge');const t=await account(env,c.from);if(t){const ts=ensure(t.data),m=ts.challenges.find(x=>x.id===c.id);if(m)m.status=c.status;await write(env,t,'Sync challenge response')}return json({ok:true,status:c.status},200,cors)}
function ensure(d){d.settings=d.settings||{};const s=d.settings.gameSocial=d.settings.gameSocial||{};for(const k of ['friends','incomingRequests','outgoingRequests','challenges'])if(!Array.isArray(s[k]))s[k]=[];return s}
async function account(env,u){const path=`users/${u}/data.json`,r=await fetch(`https://api.github.com/repos/${DATA_REPO}/contents/${path}?ref=main`,{headers:gh(env)});if(r.status===404)return null;if(!r.ok)throw Error('GitHub GET');const x=await r.json(),bytes=Uint8Array.from(atob(x.content.replace(/\n/g,'')),c=>c.charCodeAt(0));return{path,sha:x.sha,data:JSON.parse(new TextDecoder().decode(bytes))}}
async function write(env,a,msg){const content=enc(JSON.stringify(a.data,null,2)),r=await fetch(`https://api.github.com/repos/${DATA_REPO}/contents/${a.path}`,{method:'PUT',headers:{...gh(env),'Content-Type':'application/json'},body:JSON.stringify({message:msg,content,branch:'main',sha:a.sha})});if(!r.ok)throw Error('GitHub PUT')}
function gh(env){return{Authorization:`Bearer ${env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Redlighte-Game'}}
function enc(t){const b=new TextEncoder().encode(t);let s='';for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)}
function dec(t){const b=atob(t.replace(/\s/g,''));return new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0)))}
async function readSession(request,env){const m=(request.headers.get('Cookie')||'').match(/(?:^|;\s*)redlighte_session=([^;]+)/);if(!m)return null;const raw=m[1],i=raw.lastIndexOf('.');if(i<1)return null;const p=raw.slice(0,i),sig=raw.slice(i+1);try{const e=await sign(p,env.GITHUB_TOKEN);if(!safe(sig,e))return null;const d=JSON.parse(dec(p));return d.exp&&d.exp>=Date.now()?d:null}catch{return null}}
async function sign(v,s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(s),{name:'HMAC',hash:'SHA-256'},false,['sign']),x=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(v));return[...new Uint8Array(x)].map(n=>n.toString(16).padStart(2,'0')).join('')}
function safe(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function clean(v,n){return typeof v==='string'?v.trim().slice(0,n):''}function valid(v){return /^[a-z0-9][a-z0-9_.-]{2,31}$/.test(v)}
function corsHeaders(r){const o=r.headers.get('Origin'),a=o&&/^https:\/\/(?:www\.)?redlighte\.ir$/.test(o)?o:'https://redlighte.ir';return{'Access-Control-Allow-Origin':a,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Vary':'Origin'}}function json(d,s,h){return new Response(JSON.stringify(d),{status:s,headers:{...h,'Content-Type':'application/json','Cache-Control':'no-store'}})}