function RedlighteStorageManager(){this.state=window.__REDLIGHTE_2048_STATE__||{};this.bestScore=Number(this.state.bestScore)||0;this.finishedReported=false;this.saveTimer=null}
RedlighteStorageManager.prototype.getBestScore=function(){return this.bestScore};
RedlighteStorageManager.prototype.setBestScore=function(score){this.bestScore=Number(score)||0;this.state.bestScore=this.bestScore;this.queueSave()};
RedlighteStorageManager.prototype.getGameState=function(){return this.state.gameState||null};
RedlighteStorageManager.prototype.setGameState=function(gameState){this.state.gameState=gameState;this.queueSave();if(gameState.won&&!this.finishedReported){this.finishedReported=true;this.reportResult(gameState.score,true)}else if(gameState.over&&!this.finishedReported){this.finishedReported=true;this.reportResult(gameState.score,false)}};
RedlighteStorageManager.prototype.clearGameState=function(){this.state.gameState=null;this.finishedReported=false;this.queueSave()};
RedlighteStorageManager.prototype.queueSave=function(){var self=this;clearTimeout(this.saveTimer);this.saveTimer=setTimeout(function(){self.save()},350)};
RedlighteStorageManager.prototype.save=function(){var self=this;fetch('/api/account/data',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json','Cache-Control':'no-store'}}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(j){var g=Object.assign({},j.settings&&j.settings.game||{});g.game2048={bestScore:self.bestScore,state:self.state.gameState||null};return fetch('/api/account/data',{method:'PUT',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({settings:{game:g}})})}).catch(function(){})};
RedlighteStorageManager.prototype.reportResult=function(score,win){var self=this;fetch('/api/account/data',{credentials:'same-origin',cache:'no-store',headers:{Accept:'application/json','Cache-Control':'no-store'}}).then(function(r){if(!r.ok)throw 0;return r.json()}).then(function(j){var g=Object.assign({},j.settings&&j.settings.game||{});g.gamesPlayed=(Number(g.gamesPlayed)||0)+1;g.xp=(Number(g.xp)||0)+10+Math.min(30,Math.max(0,Number(score)||0));g.coins=(Number(g.coins)||0)+(win?15:5);if(win)g.wins=(Number(g.wins)||0)+1;g.extraScores=Object.assign({},g.extraScores||{},{'2048':Math.max(Number(g.extraScores&&g.extraScores['2048']||0),Number(score)||0)});g.playedGames=Array.isArray(g.playedGames)?g.playedGames.slice():[];if(!g.playedGames.includes('2048'))g.playedGames.push('2048');g.game2048={bestScore:self.bestScore,state:self.state.gameState||null};return fetch('/api/account/data',{method:'PUT',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({settings:{game:g}})})}).then(function(){return fetch('/api/game/quests/progress',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action:'play',amount:1})})}).then(function(){if(win)return fetch('/api/game/quests/progress',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({action:'win',amount:1})})}).then(function(){window.dispatchEvent(new Event('redlighte-game-refresh'))}).catch(function(){})};
window.addEventListener('beforeunload',function(){if(window.__REDLIGHTE_2048_MANAGER__&&window.__REDLIGHTE_2048_MANAGER__.storageManager)window.__REDLIGHTE_2048_MANAGER__.storageManager.save()});
