const DATA_URL='/articles/data/articles.json';const MORE_URL='/articles/data/articles-more.json';const REDLIGHTE_URL='/articles/data/articles-redlighte.json';
let allArticles=[];let category='all';
const $=s=>document.querySelector(s);
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function faDate(value){try{return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'long',day:'numeric'}).format(new Date(value+'T00:00:00'))}catch{return value}}
function categoryName(value){return ({ai:'هوش مصنوعی',technology:'تکنولوژی',tutorials:'آموزش‌ها',redlighte:'ردلایت'})[value]||value}
function sortNewest(a,b){const dateA=Date.parse(a.publishedAt||a.updatedAt||'')||0;const dateB=Date.parse(b.publishedAt||b.updatedAt||'')||0;return dateB-dateA}
function render(){const q=$('#search').value.trim().toLowerCase();const list=allArticles.filter(a=>(category==='all'||a.category===category)&&(!q||`${a.title} ${a.description} ${a.category} ${(a.tags||[]).join(' ')} ${(a.keywords||[]).join(' ')}`.toLowerCase().includes(q))).sort(sortNewest);const featured=$('#featured');if(list.length&&!q){const a=list[0];featured.innerHTML=`<a class="featured-card fade" href="${esc(a.url)}"><div class="featured-visual"><span class="featured-kicker">🔥 داغ‌ترین مقاله</span></div><div class="featured-copy"><p class="eyebrow">${esc(categoryName(a.category))} · ${esc(faDate(a.publishedAt))}</p><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><div class="featured-meta"><span>${esc(a.readingTime)} دقیقه مطالعه</span><span class="featured-read">مطالعه مقاله ←</span></div></div></a>`}else featured.innerHTML='';$('#empty').hidden=list.length>0;$('#articles').innerHTML=list.map((a,i)=>`<a class="card fade" style="animation-delay:${Math.min(i*45,300)}ms" href="${esc(a.url)}"><div class="card-top"><span class="category">${esc(categoryName(a.category))}</span></div><h3>${esc(a.title)}</h3><p>${esc(a.description)}</p><div class="meta"><span>${esc(a.readingTime)} دقیقه مطالعه</span><span>${esc(faDate(a.publishedAt))}</span></div></a>`).join('')}
Promise.all([fetch(DATA_URL).then(r=>r.json()),fetch(MORE_URL).then(r=>r.json()),fetch(REDLIGHTE_URL).then(r=>r.json())]).then(([base,more,redlighte])=>{allArticles=[...(base.articles||[]),...(more.articles||[]),...(redlighte.articles||[])];render()}).catch(()=>{$('#empty').hidden=false});
$('#filters').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;category=b.dataset.category;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#search').addEventListener('input',render);
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus()}});