(()=>{
  const style=document.createElement('style');
  style.textContent=`
  .rl-engagement{margin:42px 0 0;padding:14px 16px;border:1px solid rgba(255,255,255,.12);border-radius:22px;background:linear-gradient(135deg,rgba(255,255,255,.075),rgba(255,255,255,.025));box-shadow:0 18px 55px rgba(0,0,0,.22),inset 0 1px rgba(255,255,255,.08);backdrop-filter:blur(24px) saturate(135%);-webkit-backdrop-filter:blur(24px) saturate(135%)}
  .rl-engagement-actions{display:flex;align-items:center;gap:9px;direction:rtl}.rl-engagement-btn{appearance:none;border:1px solid rgba(255,255,255,.09);background:rgba(255,255,255,.045);color:#eee;border-radius:15px;padding:10px 14px;display:inline-flex;align-items:center;justify-content:center;gap:8px;font:700 12px/1 Estedad,system-ui,sans-serif;cursor:pointer;transition:transform .2s cubic-bezier(.22,1,.36,1),background .2s,border-color .2s,box-shadow .2s}.rl-engagement-btn:hover{transform:translateY(-2px);background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.16)}.rl-engagement-btn:active{transform:scale(.97)}.rl-engagement-btn.liked{color:#ff6472;background:rgba(255,48,69,.11);border-color:rgba(255,48,69,.3);box-shadow:0 8px 25px rgba(255,48,69,.12)}.rl-engagement-count{color:#999;font-weight:600}.rl-engagement-share{margin-right:auto}.rl-comments{margin-top:16px;display:none;padding-top:16px;border-top:1px solid rgba(255,255,255,.08)}.rl-comments.open{display:block}.rl-comments-title{font-size:14px;font-weight:800;margin:0 0 14px}.rl-comment-form{display:flex;gap:8px;margin-bottom:18px}.rl-comment-input{flex:1;min-width:0;resize:vertical;min-height:46px;max-height:140px;border:1px solid rgba(255,255,255,.1);border-radius:14px;background:rgba(0,0,0,.22);color:#fff;padding:12px 13px;outline:none;font:500 13px/1.8 Estedad,system-ui,sans-serif}.rl-comment-input:focus{border-color:rgba(255,100,114,.5);box-shadow:0 0 0 3px rgba(255,48,69,.08)}.rl-comment-send{border:0;border-radius:14px;padding:0 16px;background:#ff3045;color:#fff;font:800 12px Estedad,system-ui,sans-serif;cursor:pointer}.rl-comment-list{display:grid;gap:10px}.rl-comment{padding:13px 14px;border-radius:15px;background:rgba(255,255,255,.035);border:1px solid rgba(255,255,255,.06)}.rl-comment-head{display:flex;align-items:center;gap:8px;font-size:11px;color:#888;margin-bottom:7px}.rl-comment-avatar{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:rgba(255,48,69,.16);color:#ff6472;font-weight:800}.rl-comment-name{color:#ddd;font-weight:800}.rl-comment-text{margin:0;color:#ccc;font-size:13px;line-height:1.9;white-space:pre-wrap;word-break:break-word}.rl-comment-empty,.rl-comment-note{color:#777;font-size:12px;line-height:1.8}.rl-engagement-toast{position:fixed;left:50%;bottom:22px;transform:translate(-50%,12px);opacity:0;pointer-events:none;z-index:9999;padding:10px 15px;border:1px solid rgba(255,255,255,.12);border-radius:13px;background:rgba(18,18,20,.82);backdrop-filter:blur(18px);color:#fff;font:600 12px Estedad,system-ui,sans-serif;transition:.25s}.rl-engagement-toast.show{opacity:1;transform:translate(-50%,0)}
  @media(max-width:600px){.rl-engagement{margin-top:34px;padding:12px}.rl-engagement-actions{gap:7px}.rl-engagement-btn{flex:1;padding:11px 8px;font-size:11px}.rl-engagement-share{margin-right:0}.rl-comment-form{flex-direction:column}.rl-comment-send{min-height:44px}.rl-comments-title{font-size:13px}}
  `;document.head.appendChild(style);

  const article=document.querySelector('article');
  if(!article)return;
  const slug=location.pathname.replace(/^\/articles\//,'').replace(/\/$/,'').split('/')[0];
  if(!slug||['ai','game','redlighte','technology','tech-news','tutorials'].includes(slug)&&location.pathname==='/articles/'+slug+'/'){
    // category/index pages are not article detail pages
    if(!document.querySelector('article h1'))return;
  }
  const mount=document.createElement('section');mount.className='rl-engagement';mount.setAttribute('aria-label','تعامل با مقاله');
  mount.innerHTML=`<div class="rl-engagement-actions"><button class="rl-engagement-btn rl-like" type="button" aria-label="لایک مقاله">♥ <span>لایک</span> <span class="rl-engagement-count">0</span></button><button class="rl-engagement-btn rl-comment-toggle" type="button" aria-label="نمایش کامنت‌ها">💬 <span>کامنت</span> <span class="rl-engagement-count">0</span></button><button class="rl-engagement-btn rl-engagement-share" type="button" aria-label="اشتراک‌گذاری مقاله">↗ <span>شیر</span></button></div><div class="rl-comments"><h3 class="rl-comments-title">نظرات</h3><div class="rl-comment-form"><textarea class="rl-comment-input" maxlength="1000" placeholder="نظرت درباره این مقاله چیه؟"></textarea><button class="rl-comment-send" type="button">ارسال</button></div><div class="rl-comment-list"></div></div>`;
  const nav=article.querySelector('.article-nav');
  if(nav)nav.before(mount);else article.appendChild(mount);
  const toast=document.createElement('div');toast.className='rl-engagement-toast';document.body.appendChild(toast);
  let toastTimer;const showToast=(t)=>{toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),2200)};
  const likeBtn=mount.querySelector('.rl-like'),commentBtn=mount.querySelector('.rl-comment-toggle'),shareBtn=mount.querySelector('.rl-engagement-share'),comments=mount.querySelector('.rl-comments'),input=mount.querySelector('.rl-comment-input'),send=mount.querySelector('.rl-comment-send'),list=mount.querySelector('.rl-comment-list');
  const counts=mount.querySelectorAll('.rl-engagement-count');
  let state={liked:false,likes:0,comments:[]};
  const render=()=>{counts[0].textContent=state.likes;counts[1].textContent=state.comments.length;likeBtn.classList.toggle('liked',state.liked);list.innerHTML=state.comments.length?state.comments.map(c=>`<div class="rl-comment"><div class="rl-comment-head"><span class="rl-comment-avatar">${escapeHtml((c.name||'?').trim().charAt(0).toUpperCase())}</span><span class="rl-comment-name">${escapeHtml(c.name||'کاربر')}</span><span>•</span><span>${formatDate(c.createdAt)}</span></div><p class="rl-comment-text">${escapeHtml(c.text||'')}</p></div>`).join(''):'<div class="rl-comment-empty">هنوز نظری ثبت نشده. اولین نفری باش که نظر می‌ده ✨</div>';};
  const load=async()=>{try{const r=await fetch('/api/articles/engagement?slug='+encodeURIComponent(slug),{credentials:'include',cache:'no-store'});if(!r.ok)throw 0;state=await r.json();render()}catch{render()}};
  likeBtn.onclick=async()=>{try{const r=await fetch('/api/articles/engagement',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:state.liked?'unlike':'like',slug})});const d=await r.json().catch(()=>({}));if(r.status===401){showToast('برای لایک کردن وارد حساب ردلایت شو.');return}if(!r.ok)throw 0;state.likes=d.likes;state.liked=d.liked;render()}catch{showToast('ثبت لایک انجام نشد؛ دوباره تلاش کن.')}};
  commentBtn.onclick=()=>{comments.classList.toggle('open');if(comments.classList.contains('open')){input.focus();comments.scrollIntoView({behavior:'smooth',block:'nearest'})}};
  send.onclick=async()=>{const text=input.value.trim();if(!text)return;send.disabled=true;try{const r=await fetch('/api/articles/engagement',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'comment',slug,text})});const d=await r.json().catch(()=>({}));if(r.status===401){showToast('برای کامنت گذاشتن وارد حساب ردلایت شو.');return}if(!r.ok)throw 0;state.comments=d.comments||state.comments;input.value='';comments.classList.add('open');render();showToast('کامنتت ثبت شد ❤️')}catch{showToast('ثبت کامنت انجام نشد؛ دوباره تلاش کن.')}finally{send.disabled=false}};
  shareBtn.onclick=async()=>{try{if(navigator.share){await navigator.share({title:document.title,url:location.href})}else{await navigator.clipboard.writeText(location.href);showToast('لینک مقاله کپی شد 🔗')}}catch(e){if(e?.name!=='AbortError')showToast('اشتراک‌گذاری انجام نشد.')}};
  const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const formatDate=s=>{try{return new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'short',day:'numeric'}).format(new Date(s))}catch{return''}};
  load();
})();
